language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install:
    - pip install -U virtualenv tox-travis
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install codecov ; fi
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install coveralls -e . ; fi
before_script:
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then bash <(curl -Ls https://coverage.codacy.com/get.sh) download; fi
script:
    - tox
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install codacy-coverage && coverage run --source=fractal_python setup.py test && coverage xml; fi
after_success:
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then coveralls; fi
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then codecov; fi
    - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml; fi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: JeremyDTaylor
  password:
    secure: WYdrLIZ8f5oJ6NPV6PWdHOLEi/UgRyQx4WYI/plb3Gvo48F33VFFla79GrzxquAmb6dhGlRNZKHNR+RfuPLmN/0J8oFGOCDk4ilsMwbGeAdjfLzYdZpuFF+IPowAm55GUDXmiXzrAD/JSsLHEQlsR7Ali7JC3Pi/jhdgwX9DqRDEZd7Xg17EJwoy9N0+J8imADVRH2T80nwbXnLEmnq4ULR7dQmQQMfIqnJ1/GrQihsibzy49U3QNqCBAWrIjvUQ6TOuE+MjwKXe4ksg3nmANFDwehlHB02SSwHuLgTwMU1fM7wLOia4m1oJP6Qad4n68zfLb+OQCkLL48gpSTrNcGby66U/Q5lmmxxslaMxMZYsYtkVGX6y7+OGTdHUArMfjRIVZpvwYKkVyrNjkADVNtSiG0GhQOuza+yn3KhT4Dnq1jGGEunkfA4bXyiQDlorbxXmKWqeKVyTlIcW4dTBr7ukXjL5nIyp0d+VhzagCixZ7RMYv5AzVaCjA2qmqWwLJjHzJxTZge9MrXO9IY/tBEKdNQw6+gYFIXqgoY4dMIeEv4nZf+/IF0eHMOfDqZ3J1Mifi5CKqECcvsvEf0JowdYHoxFdcy/l0tK3EK9BBQX+TTb6+LYmOEWdaoHr1Y+7ZU3PDIpQSd4dDsmUTMPVNqOHMbpJoa44mr9lfba0cVA=
  on:
    tags: true
    repo: JeremyDTaylor/fractal_python
    python: 3.9
